import java.util.Scanner;
public class StringIDCreator {
    public static void main(String[] args){
        Scanner kb = new Scanner(System.in);

        System.out.print("How many string ID(s) do you want?: ");
        int size = kb.nextInt();
    
        String[] arrayID = stringID(size); // creates another string array based on the returned data
        System.out.println("Here are your autogenerated uniqueID(s)!: ");
        for(int i = 0; i<arrayID.length; i++){ // prints out the returned string array
            System.out.println(arrayID[i]);
        }
    }
    static String[] stringID(int size){ // take inputted int size and converts it to a string
        String[] arrayID = new String[size]; // creates an array and size is based on user's inputted size int value

        for(int i = 0; i<arrayID.length; i++){
            String s = Integer.toString(i+1); // int to string conversion
            String nameID = ("uniqueID_"+ s); // assigning the converted string number to the uniqueID_ string
            arrayID[i] = nameID; // adds the name ID to the current index position
        }
        return arrayID;
    }
}
